// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/mesh/proto/mesh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlFrame is the top-level envelope for all control plane messages.
// Each frame carries exactly one payload via oneof.
type ControlFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlFrame_Gossip
	//	*ControlFrame_WhoHas
	//	*ControlFrame_IHave
	//	*ControlFrame_CredRequest
	//	*ControlFrame_CredGrant
	//	*ControlFrame_RelayOpen
	//	*ControlFrame_RelayAccept
	//	*ControlFrame_Bootstrap
	Payload       isControlFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlFrame) Reset() {
	*x = ControlFrame{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFrame) ProtoMessage() {}

func (x *ControlFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFrame.ProtoReflect.Descriptor instead.
func (*ControlFrame) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *ControlFrame) GetPayload() isControlFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlFrame) GetGossip() *GossipFrame {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_Gossip); ok {
			return x.Gossip
		}
	}
	return nil
}

func (x *ControlFrame) GetWhoHas() *WhoHasFrame {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_WhoHas); ok {
			return x.WhoHas
		}
	}
	return nil
}

func (x *ControlFrame) GetIHave() *IHaveFrame {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_IHave); ok {
			return x.IHave
		}
	}
	return nil
}

func (x *ControlFrame) GetCredRequest() *CredentialRequestFrame {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_CredRequest); ok {
			return x.CredRequest
		}
	}
	return nil
}

func (x *ControlFrame) GetCredGrant() *CredentialGrantFrame {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_CredGrant); ok {
			return x.CredGrant
		}
	}
	return nil
}

func (x *ControlFrame) GetRelayOpen() *RelayOpenFrame {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_RelayOpen); ok {
			return x.RelayOpen
		}
	}
	return nil
}

func (x *ControlFrame) GetRelayAccept() *RelayAcceptFrame {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_RelayAccept); ok {
			return x.RelayAccept
		}
	}
	return nil
}

func (x *ControlFrame) GetBootstrap() *BootstrapFrame {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_Bootstrap); ok {
			return x.Bootstrap
		}
	}
	return nil
}

type isControlFrame_Payload interface {
	isControlFrame_Payload()
}

type ControlFrame_Gossip struct {
	Gossip *GossipFrame `protobuf:"bytes,1,opt,name=gossip,proto3,oneof"`
}

type ControlFrame_WhoHas struct {
	WhoHas *WhoHasFrame `protobuf:"bytes,2,opt,name=who_has,json=whoHas,proto3,oneof"`
}

type ControlFrame_IHave struct {
	IHave *IHaveFrame `protobuf:"bytes,3,opt,name=i_have,json=iHave,proto3,oneof"`
}

type ControlFrame_CredRequest struct {
	CredRequest *CredentialRequestFrame `protobuf:"bytes,4,opt,name=cred_request,json=credRequest,proto3,oneof"`
}

type ControlFrame_CredGrant struct {
	CredGrant *CredentialGrantFrame `protobuf:"bytes,5,opt,name=cred_grant,json=credGrant,proto3,oneof"`
}

type ControlFrame_RelayOpen struct {
	RelayOpen *RelayOpenFrame `protobuf:"bytes,6,opt,name=relay_open,json=relayOpen,proto3,oneof"`
}

type ControlFrame_RelayAccept struct {
	RelayAccept *RelayAcceptFrame `protobuf:"bytes,7,opt,name=relay_accept,json=relayAccept,proto3,oneof"`
}

type ControlFrame_Bootstrap struct {
	Bootstrap *BootstrapFrame `protobuf:"bytes,8,opt,name=bootstrap,proto3,oneof"`
}

func (*ControlFrame_Gossip) isControlFrame_Payload() {}

func (*ControlFrame_WhoHas) isControlFrame_Payload() {}

func (*ControlFrame_IHave) isControlFrame_Payload() {}

func (*ControlFrame_CredRequest) isControlFrame_Payload() {}

func (*ControlFrame_CredGrant) isControlFrame_Payload() {}

func (*ControlFrame_RelayOpen) isControlFrame_Payload() {}

func (*ControlFrame_RelayAccept) isControlFrame_Payload() {}

func (*ControlFrame_Bootstrap) isControlFrame_Payload() {}

// GossipFrame carries impedance cost-vectors and capability data for
// gradient routing. Sent periodically to all direct peers.
//
// Capabilities propagate transitively through gossip, just like routes:
// if B learns C's capabilities from C, B includes them in its gossip to A.
// This enables full mesh-wide capability convergence without broadcast.
type GossipFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id of the node emitting this gossip.
	FromNode string `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	// Cost vector: map of reachable node-id → total impedance cost.
	Routes map[string]float64 `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Current impedance of the sending node.
	// Used by the receiver as the "last mile" cost when computing
	// total route costs: totalCost = route.Cost + from_impedance.
	FromImpedance float64 `protobuf:"fixed64,3,opt,name=from_impedance,json=fromImpedance,proto3" json:"from_impedance,omitempty"`
	// Capabilities of the sending node itself.
	// Always included — this is the cheapest path to learn a direct
	// peer's capabilities (no extra round trip, no broadcast).
	FromCapabilities []string `protobuf:"bytes,4,rep,name=from_capabilities,json=fromCapabilities,proto3" json:"from_capabilities,omitempty"`
	// Capabilities of other nodes the sender has learned about
	// (transitively via gossip from its own peers).
	// Capped to the same budget-derived horizon as routes.
	NodeCapabilities map[string]*NodeCapabilities `protobuf:"bytes,5,rep,name=node_capabilities,json=nodeCapabilities,proto3" json:"node_capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GossipFrame) Reset() {
	*x = GossipFrame{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipFrame) ProtoMessage() {}

func (x *GossipFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipFrame.ProtoReflect.Descriptor instead.
func (*GossipFrame) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *GossipFrame) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *GossipFrame) GetRoutes() map[string]float64 {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GossipFrame) GetFromImpedance() float64 {
	if x != nil {
		return x.FromImpedance
	}
	return 0
}

func (x *GossipFrame) GetFromCapabilities() []string {
	if x != nil {
		return x.FromCapabilities
	}
	return nil
}

func (x *GossipFrame) GetNodeCapabilities() map[string]*NodeCapabilities {
	if x != nil {
		return x.NodeCapabilities
	}
	return nil
}

// NodeCapabilities carries a node's capability list.
// Used inside GossipFrame.node_capabilities for transitive propagation.
type NodeCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCapabilities) Reset() {
	*x = NodeCapabilities{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapabilities) ProtoMessage() {}

func (x *NodeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapabilities.ProtoReflect.Descriptor instead.
func (*NodeCapabilities) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *NodeCapabilities) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// WhoHasFrame is a broadcast discovery request.
// Forwarded to all peers except the origin (flood-fill).
//
// Flood termination (P1-2): max_hops bounds the number of times this
// frame may be relayed. The originator stamps it based on expected
// mesh diameter (grows as log(N), not N). Each forwarder decrements
// max_hops; when a receiver sees max_hops == 0 it processes locally
// but does not forward. Loop termination becomes a correctness
// guarantee independent of any seen-set size.
type WhoHasFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request ID for deduplication (UUID v4).
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The capability being searched for (e.g., "tool:lustre_health").
	Capability string `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	// Node that originated this request.
	OriginNode string `protobuf:"bytes,3,opt,name=origin_node,json=originNode,proto3" json:"origin_node,omitempty"`
	// Remaining hop budget. Originator sets to expected mesh
	// diameter; each forwarder decrements before relaying; zero
	// means "do not forward further."
	MaxHops       uint32 `protobuf:"varint,4,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoHasFrame) Reset() {
	*x = WhoHasFrame{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoHasFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoHasFrame) ProtoMessage() {}

func (x *WhoHasFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoHasFrame.ProtoReflect.Descriptor instead.
func (*WhoHasFrame) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *WhoHasFrame) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *WhoHasFrame) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *WhoHasFrame) GetOriginNode() string {
	if x != nil {
		return x.OriginNode
	}
	return ""
}

func (x *WhoHasFrame) GetMaxHops() uint32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

// IHaveFrame is a unicast response to a WhoHas request.
// Routed back toward the origin node via gradient routing.
type IHaveFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID matching the original WhoHas request.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Node that has the requested capability.
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Current impedance of the responding node.
	Impedance float64 `protobuf:"fixed64,3,opt,name=impedance,proto3" json:"impedance,omitempty"`
	// Node that originated the WhoHas query.
	// Used for gradient routing of the response back to the origin.
	OriginNode    string `protobuf:"bytes,4,opt,name=origin_node,json=originNode,proto3" json:"origin_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IHaveFrame) Reset() {
	*x = IHaveFrame{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IHaveFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IHaveFrame) ProtoMessage() {}

func (x *IHaveFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IHaveFrame.ProtoReflect.Descriptor instead.
func (*IHaveFrame) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *IHaveFrame) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *IHaveFrame) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *IHaveFrame) GetImpedance() float64 {
	if x != nil {
		return x.Impedance
	}
	return 0
}

func (x *IHaveFrame) GetOriginNode() string {
	if x != nil {
		return x.OriginNode
	}
	return ""
}

// CredentialRequestFrame requests SSH/TLS credentials for a host.
// Point-to-point ONLY — never broadcast or forwarded.
//
// Replay protection (P0-3): every request carries a per-request nonce
// and a requester-supplied timestamp. The granter binds the sealed
// grant to the nonce (see SealGrantWithNonce) and rejects requests
// outside a clock-skew window so captured-and-replayed request frames
// cannot be reused past credential rotation.
type CredentialRequestFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host pattern or hostname needing credentials.
	HostPattern string `protobuf:"bytes,1,opt,name=host_pattern,json=hostPattern,proto3" json:"host_pattern,omitempty"`
	// Ed25519 public key of the requester (for NaCl box sealing).
	RequesterPubKey []byte `protobuf:"bytes,2,opt,name=requester_pub_key,json=requesterPubKey,proto3" json:"requester_pub_key,omitempty"`
	// Per-request nonce (32 bytes from crypto/rand). The granter
	// embeds this in the sealed payload so the requester can verify
	// the grant was issued for this specific request. Required.
	Nonce []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// UnixNano timestamp when the requester built this frame. The
	// granter rejects requests outside a configurable clock-skew
	// window (default ±2 minutes). Required.
	RequestedAt   int64 `protobuf:"varint,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialRequestFrame) Reset() {
	*x = CredentialRequestFrame{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialRequestFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRequestFrame) ProtoMessage() {}

func (x *CredentialRequestFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRequestFrame.ProtoReflect.Descriptor instead.
func (*CredentialRequestFrame) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *CredentialRequestFrame) GetHostPattern() string {
	if x != nil {
		return x.HostPattern
	}
	return ""
}

func (x *CredentialRequestFrame) GetRequesterPubKey() []byte {
	if x != nil {
		return x.RequesterPubKey
	}
	return nil
}

func (x *CredentialRequestFrame) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *CredentialRequestFrame) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

// CredentialGrantFrame delivers sealed credentials to the requester.
// Point-to-point ONLY — never broadcast or forwarded.
type CredentialGrantFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NaCl box sealed to the requester's public key.
	// Contains ephemeral pub (32) + nonce (24) + encrypted Credential JSON.
	SealedCredential []byte `protobuf:"bytes,1,opt,name=sealed_credential,json=sealedCredential,proto3" json:"sealed_credential,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CredentialGrantFrame) Reset() {
	*x = CredentialGrantFrame{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialGrantFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialGrantFrame) ProtoMessage() {}

func (x *CredentialGrantFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialGrantFrame.ProtoReflect.Descriptor instead.
func (*CredentialGrantFrame) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *CredentialGrantFrame) GetSealedCredential() []byte {
	if x != nil {
		return x.SealedCredential
	}
	return nil
}

// RelayOpenFrame requests the next-hop peer to open a circuit
// to the target node and stitch streams together.
type RelayOpenFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target node to relay to.
	TargetNodeId string `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	// Unique circuit ID for matching the accept response.
	CircuitId     string `protobuf:"bytes,2,opt,name=circuit_id,json=circuitId,proto3" json:"circuit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayOpenFrame) Reset() {
	*x = RelayOpenFrame{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayOpenFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayOpenFrame) ProtoMessage() {}

func (x *RelayOpenFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayOpenFrame.ProtoReflect.Descriptor instead.
func (*RelayOpenFrame) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *RelayOpenFrame) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *RelayOpenFrame) GetCircuitId() string {
	if x != nil {
		return x.CircuitId
	}
	return ""
}

// RelayAcceptFrame confirms that the relay circuit is established.
type RelayAcceptFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Circuit ID matching the RelayOpenFrame.
	CircuitId string `protobuf:"bytes,1,opt,name=circuit_id,json=circuitId,proto3" json:"circuit_id,omitempty"`
	// True if the relay was successfully established.
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success is false.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayAcceptFrame) Reset() {
	*x = RelayAcceptFrame{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayAcceptFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayAcceptFrame) ProtoMessage() {}

func (x *RelayAcceptFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayAcceptFrame.ProtoReflect.Descriptor instead.
func (*RelayAcceptFrame) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *RelayAcceptFrame) GetCircuitId() string {
	if x != nil {
		return x.CircuitId
	}
	return ""
}

func (x *RelayAcceptFrame) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RelayAcceptFrame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BootstrapFrame carries topology knowledge to a newly joined peer.
// Sent once during peer initialization (in initPeerControlPlane).
// Contains a chunk of the sender's resolver cache. Large caches are
// split into multiple frames to stay under MaxFrameSize (256KB).
type BootstrapFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of hostname → host entry, representing known hosts.
	Hosts map[string]*HostEntry `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Pagination: zero-based sequence number for this chunk.
	Sequence uint32 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Pagination: total number of chunks being sent.
	Total uint32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	// The wire-level protocol version of the sender.
	ProtocolVersion uint32 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// The application version (git short commit) of the sender.
	ApplicationVersion []byte `protobuf:"bytes,5,opt,name=application_version,json=applicationVersion,proto3" json:"application_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BootstrapFrame) Reset() {
	*x = BootstrapFrame{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapFrame) ProtoMessage() {}

func (x *BootstrapFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapFrame.ProtoReflect.Descriptor instead.
func (*BootstrapFrame) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *BootstrapFrame) GetHosts() map[string]*HostEntry {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *BootstrapFrame) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *BootstrapFrame) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BootstrapFrame) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *BootstrapFrame) GetApplicationVersion() []byte {
	if x != nil {
		return x.ApplicationVersion
	}
	return nil
}

// HostEntry describes a single host's addresses and transport type.
type HostEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Known network addresses (e.g., "10.0.1.1:443").
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// Transport type used to reach this host ("ssh", "https", or "").
	Transport string `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	// HTTP CONNECT proxy URL for reaching this host (e.g., "http://proxy.corp:8080").
	// Empty means direct connectivity (no proxy needed).
	ProxyUrl      string `protobuf:"bytes,3,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostEntry) Reset() {
	*x = HostEntry{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostEntry) ProtoMessage() {}

func (x *HostEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostEntry.ProtoReflect.Descriptor instead.
func (*HostEntry) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{10}
}

func (x *HostEntry) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *HostEntry) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *HostEntry) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

// PairFrame is exchanged immediately after mTLS handshake to correlate
// a control connection and data connection from the same peer session.
//
// Protocol:
//  1. Initiator sends PairFrame{token, role="control"} on conn_1
//  2. Initiator sends PairFrame{token, role="data"} on conn_2
//  3. Listener validates: same PeerID (mTLS) + same token + distinct roles
//
// Security: token is 32 bytes from crypto/rand, single-use, transmitted
// over mTLS (never plaintext). Prevents rogue connection injection,
// replay attacks, and connection confusion.
type PairFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32-byte random correlation token (crypto/rand).
	// Must match between control and data connections.
	Token []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Connection role: "control" or "data".
	Role          string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairFrame) Reset() {
	*x = PairFrame{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairFrame) ProtoMessage() {}

func (x *PairFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairFrame.ProtoReflect.Descriptor instead.
func (*PairFrame) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{11}
}

func (x *PairFrame) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *PairFrame) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// ToolRequest is sent to invoke a tool on a remote node.
type ToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name (e.g., "lustre_health").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Tool arguments as JSON bytes.
	ArgsJson      []byte `protobuf:"bytes,2,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{12}
}

func (x *ToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolRequest) GetArgsJson() []byte {
	if x != nil {
		return x.ArgsJson
	}
	return nil
}

// ToolResponse carries the result of a tool invocation.
type ToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the tool returned an error result.
	IsError bool `protobuf:"varint,1,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// Result content as JSON bytes.
	ContentJson   []byte `protobuf:"bytes,2,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{13}
}

func (x *ToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ToolResponse) GetContentJson() []byte {
	if x != nil {
		return x.ContentJson
	}
	return nil
}

// ListToolsRequest asks a node to enumerate its local tools.
type ListToolsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional category filter.
	Category      string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{14}
}

func (x *ListToolsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// ListToolsResponse enumerates available tools.
type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolInfo            `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{15}
}

func (x *ListToolsResponse) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

// ToolInfo describes a single available tool.
type ToolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_proto_mesh_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_proto_mesh_proto_rawDescGZIP(), []int{16}
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_pkg_mesh_proto_mesh_proto protoreflect.FileDescriptor

const file_pkg_mesh_proto_mesh_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/mesh/proto/mesh.proto\x12\n" +
	"cortexmesh\"\xf9\x03\n" +
	"\fControlFrame\x121\n" +
	"\x06gossip\x18\x01 \x01(\v2\x17.cortexmesh.GossipFrameH\x00R\x06gossip\x122\n" +
	"\awho_has\x18\x02 \x01(\v2\x17.cortexmesh.WhoHasFrameH\x00R\x06whoHas\x12/\n" +
	"\x06i_have\x18\x03 \x01(\v2\x16.cortexmesh.IHaveFrameH\x00R\x05iHave\x12G\n" +
	"\fcred_request\x18\x04 \x01(\v2\".cortexmesh.CredentialRequestFrameH\x00R\vcredRequest\x12A\n" +
	"\n" +
	"cred_grant\x18\x05 \x01(\v2 .cortexmesh.CredentialGrantFrameH\x00R\tcredGrant\x12;\n" +
	"\n" +
	"relay_open\x18\x06 \x01(\v2\x1a.cortexmesh.RelayOpenFrameH\x00R\trelayOpen\x12A\n" +
	"\frelay_accept\x18\a \x01(\v2\x1c.cortexmesh.RelayAcceptFrameH\x00R\vrelayAccept\x12:\n" +
	"\tbootstrap\x18\b \x01(\v2\x1a.cortexmesh.BootstrapFrameH\x00R\tbootstrapB\t\n" +
	"\apayload\"\xb5\x03\n" +
	"\vGossipFrame\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12;\n" +
	"\x06routes\x18\x02 \x03(\v2#.cortexmesh.GossipFrame.RoutesEntryR\x06routes\x12%\n" +
	"\x0efrom_impedance\x18\x03 \x01(\x01R\rfromImpedance\x12+\n" +
	"\x11from_capabilities\x18\x04 \x03(\tR\x10fromCapabilities\x12Z\n" +
	"\x11node_capabilities\x18\x05 \x03(\v2-.cortexmesh.GossipFrame.NodeCapabilitiesEntryR\x10nodeCapabilities\x1a9\n" +
	"\vRoutesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aa\n" +
	"\x15NodeCapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.cortexmesh.NodeCapabilitiesR\x05value:\x028\x01\"6\n" +
	"\x10NodeCapabilities\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\"}\n" +
	"\vWhoHasFrame\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x1f\n" +
	"\vorigin_node\x18\x03 \x01(\tR\n" +
	"originNode\x12\x19\n" +
	"\bmax_hops\x18\x04 \x01(\rR\amaxHops\"x\n" +
	"\n" +
	"IHaveFrame\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\timpedance\x18\x03 \x01(\x01R\timpedance\x12\x1f\n" +
	"\vorigin_node\x18\x04 \x01(\tR\n" +
	"originNode\"\xa0\x01\n" +
	"\x16CredentialRequestFrame\x12!\n" +
	"\fhost_pattern\x18\x01 \x01(\tR\vhostPattern\x12*\n" +
	"\x11requester_pub_key\x18\x02 \x01(\fR\x0frequesterPubKey\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12!\n" +
	"\frequested_at\x18\x04 \x01(\x03R\vrequestedAt\"C\n" +
	"\x14CredentialGrantFrame\x12+\n" +
	"\x11sealed_credential\x18\x01 \x01(\fR\x10sealedCredential\"U\n" +
	"\x0eRelayOpenFrame\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\x12\x1d\n" +
	"\n" +
	"circuit_id\x18\x02 \x01(\tR\tcircuitId\"a\n" +
	"\x10RelayAcceptFrame\x12\x1d\n" +
	"\n" +
	"circuit_id\x18\x01 \x01(\tR\tcircuitId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xac\x02\n" +
	"\x0eBootstrapFrame\x12;\n" +
	"\x05hosts\x18\x01 \x03(\v2%.cortexmesh.BootstrapFrame.HostsEntryR\x05hosts\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05total\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\rR\x0fprotocolVersion\x12/\n" +
	"\x13application_version\x18\x05 \x01(\fR\x12applicationVersion\x1aO\n" +
	"\n" +
	"HostsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.cortexmesh.HostEntryR\x05value:\x028\x01\"d\n" +
	"\tHostEntry\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\x12\x1b\n" +
	"\tproxy_url\x18\x03 \x01(\tR\bproxyUrl\"5\n" +
	"\tPairFrame\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\">\n" +
	"\vToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\targs_json\x18\x02 \x01(\fR\bargsJson\"L\n" +
	"\fToolResponse\x12\x19\n" +
	"\bis_error\x18\x01 \x01(\bR\aisError\x12!\n" +
	"\fcontent_json\x18\x02 \x01(\fR\vcontentJson\".\n" +
	"\x10ListToolsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"?\n" +
	"\x11ListToolsResponse\x12*\n" +
	"\x05tools\x18\x01 \x03(\v2\x14.cortexmesh.ToolInfoR\x05tools\"\\\n" +
	"\bToolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory2\x94\x01\n" +
	"\vToolService\x12;\n" +
	"\x06Invoke\x12\x17.cortexmesh.ToolRequest\x1a\x18.cortexmesh.ToolResponse\x12H\n" +
	"\tListTools\x12\x1c.cortexmesh.ListToolsRequest\x1a\x1d.cortexmesh.ListToolsResponseB3Z1github.com/flipfloptech/cortex-mcp/pkg/mesh/protob\x06proto3"

var (
	file_pkg_mesh_proto_mesh_proto_rawDescOnce sync.Once
	file_pkg_mesh_proto_mesh_proto_rawDescData []byte
)

func file_pkg_mesh_proto_mesh_proto_rawDescGZIP() []byte {
	file_pkg_mesh_proto_mesh_proto_rawDescOnce.Do(func() {
		file_pkg_mesh_proto_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_mesh_proto_mesh_proto_rawDesc), len(file_pkg_mesh_proto_mesh_proto_rawDesc)))
	})
	return file_pkg_mesh_proto_mesh_proto_rawDescData
}

var file_pkg_mesh_proto_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_mesh_proto_mesh_proto_goTypes = []any{
	(*ControlFrame)(nil),           // 0: cortexmesh.ControlFrame
	(*GossipFrame)(nil),            // 1: cortexmesh.GossipFrame
	(*NodeCapabilities)(nil),       // 2: cortexmesh.NodeCapabilities
	(*WhoHasFrame)(nil),            // 3: cortexmesh.WhoHasFrame
	(*IHaveFrame)(nil),             // 4: cortexmesh.IHaveFrame
	(*CredentialRequestFrame)(nil), // 5: cortexmesh.CredentialRequestFrame
	(*CredentialGrantFrame)(nil),   // 6: cortexmesh.CredentialGrantFrame
	(*RelayOpenFrame)(nil),         // 7: cortexmesh.RelayOpenFrame
	(*RelayAcceptFrame)(nil),       // 8: cortexmesh.RelayAcceptFrame
	(*BootstrapFrame)(nil),         // 9: cortexmesh.BootstrapFrame
	(*HostEntry)(nil),              // 10: cortexmesh.HostEntry
	(*PairFrame)(nil),              // 11: cortexmesh.PairFrame
	(*ToolRequest)(nil),            // 12: cortexmesh.ToolRequest
	(*ToolResponse)(nil),           // 13: cortexmesh.ToolResponse
	(*ListToolsRequest)(nil),       // 14: cortexmesh.ListToolsRequest
	(*ListToolsResponse)(nil),      // 15: cortexmesh.ListToolsResponse
	(*ToolInfo)(nil),               // 16: cortexmesh.ToolInfo
	nil,                            // 17: cortexmesh.GossipFrame.RoutesEntry
	nil,                            // 18: cortexmesh.GossipFrame.NodeCapabilitiesEntry
	nil,                            // 19: cortexmesh.BootstrapFrame.HostsEntry
}
var file_pkg_mesh_proto_mesh_proto_depIdxs = []int32{
	1,  // 0: cortexmesh.ControlFrame.gossip:type_name -> cortexmesh.GossipFrame
	3,  // 1: cortexmesh.ControlFrame.who_has:type_name -> cortexmesh.WhoHasFrame
	4,  // 2: cortexmesh.ControlFrame.i_have:type_name -> cortexmesh.IHaveFrame
	5,  // 3: cortexmesh.ControlFrame.cred_request:type_name -> cortexmesh.CredentialRequestFrame
	6,  // 4: cortexmesh.ControlFrame.cred_grant:type_name -> cortexmesh.CredentialGrantFrame
	7,  // 5: cortexmesh.ControlFrame.relay_open:type_name -> cortexmesh.RelayOpenFrame
	8,  // 6: cortexmesh.ControlFrame.relay_accept:type_name -> cortexmesh.RelayAcceptFrame
	9,  // 7: cortexmesh.ControlFrame.bootstrap:type_name -> cortexmesh.BootstrapFrame
	17, // 8: cortexmesh.GossipFrame.routes:type_name -> cortexmesh.GossipFrame.RoutesEntry
	18, // 9: cortexmesh.GossipFrame.node_capabilities:type_name -> cortexmesh.GossipFrame.NodeCapabilitiesEntry
	19, // 10: cortexmesh.BootstrapFrame.hosts:type_name -> cortexmesh.BootstrapFrame.HostsEntry
	16, // 11: cortexmesh.ListToolsResponse.tools:type_name -> cortexmesh.ToolInfo
	2,  // 12: cortexmesh.GossipFrame.NodeCapabilitiesEntry.value:type_name -> cortexmesh.NodeCapabilities
	10, // 13: cortexmesh.BootstrapFrame.HostsEntry.value:type_name -> cortexmesh.HostEntry
	12, // 14: cortexmesh.ToolService.Invoke:input_type -> cortexmesh.ToolRequest
	14, // 15: cortexmesh.ToolService.ListTools:input_type -> cortexmesh.ListToolsRequest
	13, // 16: cortexmesh.ToolService.Invoke:output_type -> cortexmesh.ToolResponse
	15, // 17: cortexmesh.ToolService.ListTools:output_type -> cortexmesh.ListToolsResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pkg_mesh_proto_mesh_proto_init() }
func file_pkg_mesh_proto_mesh_proto_init() {
	if File_pkg_mesh_proto_mesh_proto != nil {
		return
	}
	file_pkg_mesh_proto_mesh_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlFrame_Gossip)(nil),
		(*ControlFrame_WhoHas)(nil),
		(*ControlFrame_IHave)(nil),
		(*ControlFrame_CredRequest)(nil),
		(*ControlFrame_CredGrant)(nil),
		(*ControlFrame_RelayOpen)(nil),
		(*ControlFrame_RelayAccept)(nil),
		(*ControlFrame_Bootstrap)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_mesh_proto_mesh_proto_rawDesc), len(file_pkg_mesh_proto_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_mesh_proto_mesh_proto_goTypes,
		DependencyIndexes: file_pkg_mesh_proto_mesh_proto_depIdxs,
		MessageInfos:      file_pkg_mesh_proto_mesh_proto_msgTypes,
	}.Build()
	File_pkg_mesh_proto_mesh_proto = out.File
	file_pkg_mesh_proto_mesh_proto_goTypes = nil
	file_pkg_mesh_proto_mesh_proto_depIdxs = nil
}
