package firewallsummary

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"testing"

	"github.com/flipfloptech/cortex-mcp/internal/registry"
)

const nftFixture = `{"nftables": [
  {"metainfo": {"version": "1.0.9", "release_name": "Old Doc Yak #3", "json_schema_version": 1}},
  {"table": {"family": "inet", "name": "filter", "handle": 1}},
  {"chain": {"family": "inet", "table": "filter", "name": "input", "handle": 1, "type": "filter", "hook": "input", "prio": 0, "policy": "accept"}},
  {"chain": {"family": "inet", "table": "filter", "name": "forward", "handle": 2, "type": "filter", "hook": "forward", "prio": 0, "policy": "drop"}},
  {"rule": {"family": "inet", "table": "filter", "chain": "input", "handle": 4, "expr": [{"match": {"op": "==", "left": {"meta": {"key": "iifname"}}, "right": "lo"}}, {"counter": {"packets": 100, "bytes": 8000}}, {"accept": null}]}},
  {"rule": {"family": "inet", "table": "filter", "chain": "input", "handle": 5, "comment": "drop bogons", "expr": [{"counter": {"packets": 7, "bytes": 420}}, {"drop": null}]}},
  {"table": {"family": "ip", "name": "nat", "handle": 2}},
  {"chain": {"family": "ip", "table": "nat", "name": "postrouting", "handle": 1, "type": "nat", "hook": "postrouting", "prio": 100, "policy": "accept"}},
  {"rule": {"family": "ip", "table": "nat", "chain": "postrouting", "handle": 7, "expr": [{"masquerade": null}]}}
]}`

const nftEmptyFixture = `{"nftables": [{"metainfo": {"version": "1.0.9", "release_name": "Old Doc Yak #3", "json_schema_version": 1}}]}`

const iptablesSaveFixture = `# Generated by iptables-save v1.8.7 on Mon Jul  6 10:00:00 2026
*filter
:INPUT ACCEPT [530:37236]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [418:55842]
:DOCKER-USER - [0:0]
[125:7544] -A INPUT -i lo -j ACCEPT
[3:180] -A INPUT -m conntrack --ctstate INVALID -j DROP
[0:0] -A FORWARD -j DOCKER-USER
COMMIT
*nat
:PREROUTING ACCEPT [100:6000]
:POSTROUTING ACCEPT [50:3000]
-A POSTROUTING -s 172.17.0.0/16 -j MASQUERADE
COMMIT
# Completed
`

const iptablesSFixture = `-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N MYCHAIN
-A INPUT -i lo -j ACCEPT
-A MYCHAIN -j RETURN
`

// mockLookPath returns an execLookPath stub where only the listed binaries exist.
func mockLookPath(available ...string) func(string) (string, error) {
	return func(file string) (string, error) {
		for _, a := range available {
			if a == file {
				return "/mock/bin/" + file, nil
			}
		}
		return "", errors.New("executable file not found in $PATH")
	}
}

// mockTool builds a tool whose exec layer serves canned output per binary name.
func mockTool(t testing.TB, outputs map[string]string, available ...string) *Tool {
	t.Helper()
	tool := New()
	tool.execLookPath = mockLookPath(available...)
	tool.execCommand = func(ctx context.Context, name string, args ...string) ([]byte, error) {
		// Unwrap 'sudo -n <binary> ...' invocations.
		binary := name
		if name == "sudo" && len(args) >= 2 {
			binary = args[1]
		}
		if out, ok := outputs[binary]; ok {
			return []byte(out), nil
		}
		return nil, fmt.Errorf("mock: no output configured for %q", binary)
	}
	return tool
}

func TestContractCompliance(t *testing.T) {
	t.Parallel()

	tool := New()
	var _ registry.Tool = tool

	if tool.Name() != "get_firewall_summary" {
		t.Errorf("expected Name() == 'get_firewall_summary', got %q", tool.Name())
	}
	if tool.Category() != registry.CategoryNetwork {
		t.Errorf("expected Category() == network, got %q", tool.Category())
	}
	if tool.Hidden() {
		t.Error("expected Hidden() == false")
	}
	if tool.Description() == "" {
		t.Error("expected non-empty Description()")
	}
	help := tool.Help()
	for _, src := range []string{"nft -j list ruleset", "iptables-save"} {
		if !strings.Contains(help, src) {
			t.Errorf("Help() must reference data source %q", src)
		}
	}

	params := tool.Parameters()
	if len(params) != 2 {
		t.Fatalf("expected 2 parameters (table, chain), got %d", len(params))
	}
	names := map[string]bool{}
	for _, p := range params {
		names[p.Name] = true
		if p.Required {
			t.Errorf("parameter %q must be optional", p.Name)
		}
		if p.Type != "string" {
			t.Errorf("parameter %q must be a string, got %q", p.Name, p.Type)
		}
	}
	if !names["table"] || !names["chain"] {
		t.Errorf("expected parameters named 'table' and 'chain', got %v", names)
	}
}

func TestIsSupported(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name      string
		available []string
		want      bool
	}{
		{"nft only", []string{"nft"}, true},
		{"iptables-save only", []string{"iptables-save"}, true},
		{"iptables only", []string{"iptables"}, true},
		{"nothing", nil, false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			tool := New()
			tool.execLookPath = mockLookPath(tc.available...)
			ok, reason := tool.IsSupported()
			if ok != tc.want {
				t.Errorf("IsSupported() = %v (%q), want %v", ok, reason, tc.want)
			}
			if !tc.want && reason == "" {
				t.Error("expected a reason when unsupported")
			}
		})
	}
}

func TestParseNftRuleset(t *testing.T) {
	t.Parallel()

	t.Run("full ruleset", func(t *testing.T) {
		t.Parallel()
		tables, total, rules, truncated, err := parseNftRuleset([]byte(nftFixture), "", "")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if truncated || rules != nil {
			t.Errorf("expected no rendered rules without a filter, got %v (truncated=%v)", rules, truncated)
		}
		if total != 3 {
			t.Errorf("expected 3 total rules, got %d", total)
		}
		if len(tables) != 2 {
			t.Fatalf("expected 2 tables, got %d: %+v", len(tables), tables)
		}

		filter := tables[0]
		if filter.Name != "filter" || filter.Family != "inet" {
			t.Errorf("unexpected table 0: %+v", filter)
		}
		if len(filter.Chains) != 2 {
			t.Fatalf("expected 2 chains in filter, got %d", len(filter.Chains))
		}
		input := filter.Chains[0]
		if input.Name != "input" || input.Policy != "accept" || input.RuleCount != 2 {
			t.Errorf("unexpected input chain: %+v", input)
		}
		if input.Packets != 107 || input.Bytes != 8420 {
			t.Errorf("expected counter sums 107/8420, got %d/%d", input.Packets, input.Bytes)
		}
		forward := filter.Chains[1]
		if forward.Name != "forward" || forward.Policy != "drop" || forward.RuleCount != 0 {
			t.Errorf("unexpected forward chain: %+v", forward)
		}

		nat := tables[1]
		if nat.Name != "nat" || nat.Family != "ip" || len(nat.Chains) != 1 || nat.Chains[0].RuleCount != 1 {
			t.Errorf("unexpected nat table: %+v", nat)
		}
	})

	t.Run("chain filter renders rules", func(t *testing.T) {
		t.Parallel()
		_, _, rules, truncated, err := parseNftRuleset([]byte(nftFixture), "filter", "input")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if truncated {
			t.Error("expected no truncation for 2 rules")
		}
		if len(rules) != 2 {
			t.Fatalf("expected 2 rendered rules, got %d: %v", len(rules), rules)
		}
		if !strings.Contains(rules[0], "handle 4") || !strings.Contains(rules[0], "iifname") {
			t.Errorf("unexpected rendered rule 0: %q", rules[0])
		}
		if !strings.Contains(rules[1], "drop bogons") {
			t.Errorf("expected comment in rendered rule 1: %q", rules[1])
		}
	})

	t.Run("rule cap at 100", func(t *testing.T) {
		t.Parallel()
		var sb strings.Builder
		sb.WriteString(`{"nftables": [{"table": {"family": "ip", "name": "big", "handle": 1}},`)
		sb.WriteString(`{"chain": {"family": "ip", "table": "big", "name": "c", "handle": 1, "policy": "accept"}}`)
		for i := 0; i < 150; i++ {
			fmt.Fprintf(&sb, `,{"rule": {"family": "ip", "table": "big", "chain": "c", "handle": %d, "expr": [{"accept": null}]}}`, i+10)
		}
		sb.WriteString(`]}`)

		tables, total, rules, truncated, err := parseNftRuleset([]byte(sb.String()), "big", "c")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if total != 150 || tables[0].Chains[0].RuleCount != 150 {
			t.Errorf("expected 150 counted rules, got total=%d", total)
		}
		if len(rules) != 100 || !truncated {
			t.Errorf("expected 100 rendered rules with truncation, got %d (truncated=%v)", len(rules), truncated)
		}
	})

	t.Run("empty ruleset", func(t *testing.T) {
		t.Parallel()
		tables, total, _, _, err := parseNftRuleset([]byte(nftEmptyFixture), "", "")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(tables) != 0 || total != 0 {
			t.Errorf("expected empty ruleset, got %d tables / %d rules", len(tables), total)
		}
	})

	t.Run("invalid JSON", func(t *testing.T) {
		t.Parallel()
		if _, _, _, _, err := parseNftRuleset([]byte("not json"), "", ""); err == nil {
			t.Error("expected error for invalid JSON")
		}
	})
}

func TestExtractRuleCounter(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name        string
		expr        string
		wantPackets uint64
		wantBytes   uint64
	}{
		{"anonymous counter", `[{"counter": {"packets": 5, "bytes": 300}}, {"accept": null}]`, 5, 300},
		{"no counter", `[{"accept": null}]`, 0, 0},
		{"named counter reference ignored", `[{"counter": "mycounter"}]`, 0, 0},
		{"two counters summed", `[{"counter": {"packets": 1, "bytes": 10}}, {"counter": {"packets": 2, "bytes": 20}}]`, 3, 30},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			var expr []json.RawMessage
			if err := json.Unmarshal([]byte(tc.expr), &expr); err != nil {
				t.Fatal(err)
			}
			p, b := extractRuleCounter(expr)
			if p != tc.wantPackets || b != tc.wantBytes {
				t.Errorf("extractRuleCounter = %d/%d, want %d/%d", p, b, tc.wantPackets, tc.wantBytes)
			}
		})
	}
}

func TestCompactJSON(t *testing.T) {
	t.Parallel()

	got := compactJSON([]byte("{\n  \"a\": 1,\n  \"b\": [1, 2]\n}"))
	if got != `{"a":1,"b":[1,2]}` {
		t.Errorf("compactJSON = %q", got)
	}
	// Invalid JSON falls back to trimmed raw text.
	if got := compactJSON([]byte("  broken{  ")); got != "broken{" {
		t.Errorf("compactJSON fallback = %q", got)
	}
}

func TestSplitCounterPrefix(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name     string
		line     string
		wantP    uint64
		wantB    uint64
		wantRest string
	}{
		{"counters present", "[125:7544] -A INPUT -i lo -j ACCEPT", 125, 7544, "-A INPUT -i lo -j ACCEPT"},
		{"no counters", "-A INPUT -i lo -j ACCEPT", 0, 0, "-A INPUT -i lo -j ACCEPT"},
		{"bare counter token", "[530:37236]", 530, 37236, ""},
		{"malformed counter", "[x:y] -A INPUT", 0, 0, "-A INPUT"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			p, b, rest := splitCounterPrefix(tc.line)
			if p != tc.wantP || b != tc.wantB || rest != tc.wantRest {
				t.Errorf("splitCounterPrefix(%q) = %d, %d, %q; want %d, %d, %q",
					tc.line, p, b, rest, tc.wantP, tc.wantB, tc.wantRest)
			}
		})
	}
}

func TestParseIptablesSave(t *testing.T) {
	t.Parallel()

	t.Run("save format with counters", func(t *testing.T) {
		t.Parallel()
		tables, total, rules, truncated, err := parseIptablesSave([]byte(iptablesSaveFixture), "", "")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if truncated || rules != nil {
			t.Errorf("expected no rendered rules without filter, got %v", rules)
		}
		if total != 4 {
			t.Errorf("expected 4 total rules, got %d", total)
		}
		if len(tables) != 2 {
			t.Fatalf("expected 2 tables, got %d: %+v", len(tables), tables)
		}

		filter := tables[0]
		if filter.Name != "filter" || filter.Family != "ip" || len(filter.Chains) != 4 {
			t.Fatalf("unexpected filter table: %+v", filter)
		}
		input := filter.Chains[0]
		if input.Name != "INPUT" || input.Policy != "ACCEPT" || input.RuleCount != 2 {
			t.Errorf("unexpected INPUT chain: %+v", input)
		}
		if input.Packets != 530 || input.Bytes != 37236 {
			t.Errorf("expected policy counters 530/37236, got %d/%d", input.Packets, input.Bytes)
		}
		docker := filter.Chains[3]
		if docker.Name != "DOCKER-USER" || docker.Policy != "" {
			t.Errorf("expected user chain without policy, got %+v", docker)
		}

		nat := tables[1]
		if nat.Name != "nat" || len(nat.Chains) != 2 || nat.Chains[1].RuleCount != 1 {
			t.Errorf("unexpected nat table: %+v", nat)
		}
	})

	t.Run("chain filter renders raw rules", func(t *testing.T) {
		t.Parallel()
		_, _, rules, _, err := parseIptablesSave([]byte(iptablesSaveFixture), "filter", "INPUT")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(rules) != 2 {
			t.Fatalf("expected 2 rendered rules, got %d: %v", len(rules), rules)
		}
		if !strings.Contains(rules[0], "-A INPUT -i lo -j ACCEPT") {
			t.Errorf("unexpected rendered rule: %q", rules[0])
		}
	})

	t.Run("iptables -S format with implicit filter table", func(t *testing.T) {
		t.Parallel()
		tables, total, _, _, err := parseIptablesSave([]byte(iptablesSFixture), "", "")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if total != 2 {
			t.Errorf("expected 2 rules, got %d", total)
		}
		if len(tables) != 1 || tables[0].Name != "filter" {
			t.Fatalf("expected implicit filter table, got %+v", tables)
		}
		if len(tables[0].Chains) != 4 {
			t.Errorf("expected 4 chains (3 builtin + MYCHAIN), got %+v", tables[0].Chains)
		}
		if tables[0].Chains[1].Name != "FORWARD" || tables[0].Chains[1].Policy != "DROP" {
			t.Errorf("unexpected FORWARD chain: %+v", tables[0].Chains[1])
		}
	})

	t.Run("empty input", func(t *testing.T) {
		t.Parallel()
		tables, total, _, _, err := parseIptablesSave([]byte(""), "", "")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(tables) != 0 || total != 0 {
			t.Errorf("expected empty result, got %+v", tables)
		}
	})
}

func TestExecuteNftBackend(t *testing.T) {
	t.Parallel()

	tool := mockTool(t, map[string]string{"nft": nftFixture}, "nft")

	res, err := tool.Execute(context.Background(), json.RawMessage(`{}`))
	if err != nil {
		t.Fatalf("unexpected hard error: %v", err)
	}
	if res.Status != registry.StatusOK {
		t.Fatalf("expected StatusOK, got %s (summary: %s)", res.Status, res.Summary)
	}

	var out Output
	if err := json.Unmarshal(res.Data, &out); err != nil {
		t.Fatalf("failed to unmarshal data: %v", err)
	}
	if out.Backend != "nftables" {
		t.Errorf("expected backend nftables, got %q", out.Backend)
	}
	if !out.FirewallActive {
		t.Error("expected firewall_active == true")
	}
	if out.TotalRules != 3 || len(out.Tables) != 2 {
		t.Errorf("unexpected totals: rules=%d tables=%d", out.TotalRules, len(out.Tables))
	}
	if out.Rules != nil {
		t.Errorf("expected no rendered rules without filter args, got %v", out.Rules)
	}
}

func TestExecuteChainFilter(t *testing.T) {
	t.Parallel()

	tool := mockTool(t, map[string]string{"nft": nftFixture}, "nft")

	res, err := tool.Execute(context.Background(), json.RawMessage(`{"table":"filter","chain":"input"}`))
	if err != nil {
		t.Fatalf("unexpected hard error: %v", err)
	}
	if res.Status != registry.StatusOK {
		t.Fatalf("expected StatusOK, got %s (summary: %s)", res.Status, res.Summary)
	}

	var out Output
	if err := json.Unmarshal(res.Data, &out); err != nil {
		t.Fatal(err)
	}
	if out.RequestedChain != "filter/input" {
		t.Errorf("expected requested_chain 'filter/input', got %q", out.RequestedChain)
	}
	if out.RequestedChainFound == nil || !*out.RequestedChainFound {
		t.Errorf("expected requested_chain_found == true, got %v", out.RequestedChainFound)
	}
	if len(out.Rules) != 2 {
		t.Errorf("expected 2 rendered rules, got %v", out.Rules)
	}
}

func TestExecuteChainFilterNotFound(t *testing.T) {
	t.Parallel()

	tool := mockTool(t, map[string]string{"nft": nftFixture}, "nft")

	res, err := tool.Execute(context.Background(), json.RawMessage(`{"table":"filter","chain":"nope"}`))
	if err != nil {
		t.Fatalf("unexpected hard error: %v", err)
	}
	if res.Status != registry.StatusOK {
		t.Fatalf("expected StatusOK (factual tool), got %s", res.Status)
	}

	var out Output
	if err := json.Unmarshal(res.Data, &out); err != nil {
		t.Fatal(err)
	}
	if out.RequestedChainFound == nil || *out.RequestedChainFound {
		t.Errorf("expected requested_chain_found == false, got %v", out.RequestedChainFound)
	}
	if len(out.Rules) != 0 {
		t.Errorf("expected no rules for missing chain, got %v", out.Rules)
	}
	if !strings.Contains(res.Summary, "not found") {
		t.Errorf("expected summary to mention the missing chain, got %q", res.Summary)
	}
}

func TestExecuteEmptyRulesetIsOK(t *testing.T) {
	t.Parallel()

	tool := mockTool(t, map[string]string{"nft": nftEmptyFixture}, "nft")

	res, err := tool.Execute(context.Background(), nil)
	if err != nil {
		t.Fatalf("unexpected hard error: %v", err)
	}
	if res.Status != registry.StatusOK {
		t.Fatalf("expected StatusOK for empty ruleset, got %s", res.Status)
	}

	var out Output
	if err := json.Unmarshal(res.Data, &out); err != nil {
		t.Fatal(err)
	}
	if out.FirewallActive {
		t.Error("expected firewall_active == false for empty ruleset")
	}
	if out.TotalRules != 0 {
		t.Errorf("expected 0 rules, got %d", out.TotalRules)
	}
}

func TestExecuteIptablesSaveFallback(t *testing.T) {
	t.Parallel()

	tool := mockTool(t, map[string]string{"iptables-save": iptablesSaveFixture}, "iptables-save")

	res, err := tool.Execute(context.Background(), nil)
	if err != nil {
		t.Fatalf("unexpected hard error: %v", err)
	}
	if res.Status != registry.StatusOK {
		t.Fatalf("expected StatusOK, got %s (summary: %s)", res.Status, res.Summary)
	}

	var out Output
	if err := json.Unmarshal(res.Data, &out); err != nil {
		t.Fatal(err)
	}
	if out.Backend != "iptables" {
		t.Errorf("expected backend iptables, got %q", out.Backend)
	}
	if out.TotalRules != 4 || !out.FirewallActive {
		t.Errorf("unexpected output: %+v", out)
	}
}

func TestExecuteNftFailsFallsBackToIptables(t *testing.T) {
	t.Parallel()

	tool := New()
	tool.execLookPath = mockLookPath("nft", "iptables-save")
	tool.execCommand = func(ctx context.Context, name string, args ...string) ([]byte, error) {
		binary := name
		if name == "sudo" && len(args) >= 2 {
			binary = args[1]
		}
		switch binary {
		case "nft":
			return []byte("internal:0:0-0: Error: Could not open netlink socket"), errors.New("exit status 1")
		case "iptables-save":
			return []byte(iptablesSaveFixture), nil
		}
		return nil, errors.New("unexpected binary")
	}

	res, err := tool.Execute(context.Background(), nil)
	if err != nil {
		t.Fatalf("unexpected hard error: %v", err)
	}
	if res.Status != registry.StatusOK {
		t.Fatalf("expected StatusOK from fallback, got %s (summary: %s)", res.Status, res.Summary)
	}

	var out Output
	if err := json.Unmarshal(res.Data, &out); err != nil {
		t.Fatal(err)
	}
	if out.Backend != "iptables" {
		t.Errorf("expected fallback to iptables backend, got %q", out.Backend)
	}
}

func TestExecuteIptablesSOnly(t *testing.T) {
	t.Parallel()

	tool := mockTool(t, map[string]string{"iptables": iptablesSFixture}, "iptables")

	res, err := tool.Execute(context.Background(), nil)
	if err != nil {
		t.Fatalf("unexpected hard error: %v", err)
	}
	if res.Status != registry.StatusOK {
		t.Fatalf("expected StatusOK, got %s (summary: %s)", res.Status, res.Summary)
	}

	var out Output
	if err := json.Unmarshal(res.Data, &out); err != nil {
		t.Fatal(err)
	}
	if out.Backend != "iptables" || out.TotalRules != 2 {
		t.Errorf("unexpected output: %+v", out)
	}
}

func TestExecutePermissionDenied(t *testing.T) {
	t.Parallel()

	tool := New()
	tool.execLookPath = mockLookPath("nft")
	tool.execCommand = func(ctx context.Context, name string, args ...string) ([]byte, error) {
		return []byte("nft: netlink: Operation not permitted"), errors.New("exit status 1")
	}

	res, err := tool.Execute(context.Background(), nil)
	if err != nil {
		t.Fatalf("expected encapsulated error result, got hard error: %v", err)
	}
	if res.Status != registry.StatusError {
		t.Fatalf("expected StatusError, got %s", res.Status)
	}
	if !strings.Contains(strings.ToLower(res.Summary), "root") {
		t.Errorf("expected summary to mention root requirement, got %q", res.Summary)
	}
}

func TestExecuteNoBinaries(t *testing.T) {
	t.Parallel()

	tool := New()
	tool.execLookPath = mockLookPath()
	tool.execCommand = func(ctx context.Context, name string, args ...string) ([]byte, error) {
		t.Fatal("execCommand must not be called when no binaries exist")
		return nil, nil
	}

	res, err := tool.Execute(context.Background(), nil)
	if err != nil {
		t.Fatalf("expected encapsulated error result, got hard error: %v", err)
	}
	if res.Status != registry.StatusError {
		t.Fatalf("expected StatusError, got %s", res.Status)
	}
}

func TestExecuteAllBackendsFail(t *testing.T) {
	t.Parallel()

	tool := New()
	tool.execLookPath = mockLookPath("nft", "iptables-save")
	tool.execCommand = func(ctx context.Context, name string, args ...string) ([]byte, error) {
		return []byte("kaboom"), errors.New("exit status 3")
	}

	res, err := tool.Execute(context.Background(), nil)
	if err != nil {
		t.Fatalf("expected encapsulated error result, got hard error: %v", err)
	}
	if res.Status != registry.StatusError {
		t.Fatalf("expected StatusError, got %s", res.Status)
	}
}

func TestExecuteInvalidArgs(t *testing.T) {
	t.Parallel()

	tool := mockTool(t, map[string]string{"nft": nftFixture}, "nft")

	res, err := tool.Execute(context.Background(), json.RawMessage(`{"table": 42`))
	if err != nil {
		t.Fatalf("expected encapsulated error result, got hard error: %v", err)
	}
	if res.Status != registry.StatusError {
		t.Fatalf("expected StatusError for malformed args, got %s", res.Status)
	}
}

func TestExecuteContextCancelled(t *testing.T) {
	t.Parallel()

	tool := mockTool(t, map[string]string{"nft": nftFixture}, "nft")

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	res, err := tool.Execute(ctx, nil)
	if err != nil {
		t.Fatalf("expected encapsulated error result, got hard error: %v", err)
	}
	if res.Status != registry.StatusError {
		t.Fatalf("expected StatusError for cancelled context, got %s", res.Status)
	}
	if !strings.Contains(strings.ToLower(res.Summary), "cancel") {
		t.Errorf("expected summary to mention cancellation, got %q", res.Summary)
	}
}

func TestRunPrivilegedInvocation(t *testing.T) {
	t.Parallel()

	tool := New()
	var gotName string
	var gotArgs []string
	tool.execLookPath = mockLookPath() // no sudo
	tool.execCommand = func(ctx context.Context, name string, args ...string) ([]byte, error) {
		gotName = name
		gotArgs = args
		return []byte("ok"), nil
	}

	if _, err := tool.runPrivileged(context.Background(), "nft", "-j", "list", "ruleset"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	full := gotName + " " + strings.Join(gotArgs, " ")
	if !strings.Contains(full, "nft") || !strings.Contains(full, "-j list ruleset") {
		t.Errorf("unexpected invocation: %q", full)
	}
}

func TestRenderNftRule(t *testing.T) {
	t.Parallel()

	var expr []json.RawMessage
	if err := json.Unmarshal([]byte(`[{"accept": null}]`), &expr); err != nil {
		t.Fatal(err)
	}
	rule := &nftRule{Family: "inet", Table: "filter", Chain: "input", Handle: 9, Comment: "hi", Expr: expr}
	got := renderNftRule(rule)
	for _, want := range []string{"handle 9", "accept", "hi"} {
		if !strings.Contains(got, want) {
			t.Errorf("expected rendered rule to contain %q, got %q", want, got)
		}
	}
}
