package mesh

// Tool plugin imports — each import triggers init() registration.
//
// To add a new tool to the binary, create a package under
// internal/registry/tools/<name>/ that implements registry.Tool
// and calls registry.Register() in init(), then add an import here.
//
// The PluginRegistry evaluates each tool's IsSupported() at startup.
// Unsupported tools are logged and excluded — zero runtime cost.
import (
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/arpneighbors"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/blockscheduler"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/blocktopology"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/bondstatus"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/buddyinfo"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/cgrouplimits"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/conntracksummary"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/containerinventory"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/coredumps"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/cpupowerstate"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/cputopology"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/diskio"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/dmiinventory"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/ethhardwarestats"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/filelocks"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/firewallsummary"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/gpustatus"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/hugepageinfo"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/infinibandstatus"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/ipmisel"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/irqaffinity"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/kernelmodules"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/kernelsecuritystate"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/lnetstatus"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/loadavg"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/loggedinsessions"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/lustreclientstats"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/lustreserverstats"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/memoryinfo"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/moduleinfo"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/mountusage"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/multipathstatus"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/networkinterfaces"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/nfsclientstats"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/nicethtoolstats"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/numaedacerrors"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/numastats"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/nvmesmartlog"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/openfilelimits"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/openfiles"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/packageaudit"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/pcilinkstatus"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/pressurestall"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/processlist"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/processmemorydetail"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/processtree"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/querydmesg"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/queryjournalctl"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/raidhealth"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/routingrules"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/routingtable"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/scheduledjobs"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/sensorreadings"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/slabinfo"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/smarthealth"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/socketstats"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/sysctltuning"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/sysinfo"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/systemdstatus"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/threadwchan"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/timesync"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/uptime"
	_ "github.com/flipfloptech/cortex-mcp/internal/registry/tools/zfsstatus"
)
